name: CI/CD

on:
  push:
    branches:
      - test
      - release

jobs:
  test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r GithubActionScripts/requirements.txt

      - name: Run test script
        run: python3 GithubActionScripts/model_promoter.py http://192.168.23.28:5000 http://192.168.23.28:5001

  deploy:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r GithubActionScripts/requirements.txt

      - name: Run deploy script
        run: python3 GithubActionScripts/model_promoter.py 192.168.23.28:5001 192.168.23.28:5002
