name: CI/CD

on:
  push:
    branches:
      - test
      - release

jobs:
  test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r GithubActionScripts/requirements.txt

      - name: Run test script
        run: python3 GithubActionScripts/model_promoter.py http://ec2-44-231-213-30.us-west-2.compute.amazonaws.com:5000 http://ec2-44-231-213-30.us-west-2.compute.amazonaws.com:5001

  deploy:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r GithubActionScripts/requirements.txt

      - name: Run deploy script
        run: python3 GithubActionScripts/model_promoter.py ec2-44-231-213-30.us-west-2.compute.amazonaws.com:5001 ec2-44-231-213-30.us-west-2.compute.amazonaws.com:5002
