name: CI/CD

on:
  push:
    branches:
      - test
      - release

jobs:
  test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test script
        run: python3 test_script.py

  deploy:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deploy script
        run: python3 deploy_script.py
